AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: OrdersTable
        ENDPOINT_OVERRIDE: ''
Resources:
  GetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://coforge-bucket-nd-065/a3f46d2f913672bc6f6e620cd9729de0
      Handler: com.amazonaws.handler.GetOrderHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: OrdersTable
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /orders/{order_id}
            Method: get
    Metadata:
      SamResourceId: GetOrderFunction
  GetOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://coforge-bucket-nd-065/a3f46d2f913672bc6f6e620cd9729de0
      Handler: com.amazonaws.handler.GetOrdersHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: OrdersTable
      Events:
        GetOrders:
          Type: Api
          Properties:
            Path: /orders
            Method: get
    Metadata:
      SamResourceId: GetOrdersFunction
  UpdateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://coforge-bucket-nd-065/a3f46d2f913672bc6f6e620cd9729de0
      Handler: com.amazonaws.handler.UpdateOrderHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: OrdersTable
      Events:
        UpdateOrder:
          Type: Api
          Properties:
            Path: /orders/{order_id}
            Method: post
    Metadata:
      SamResourceId: UpdateOrderFunction
  DeleteOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://coforge-bucket-nd-065/a3f46d2f913672bc6f6e620cd9729de0
      Handler: com.amazonaws.handler.DeleteOrderHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: OrdersTable
      Events:
        DeleteOrder:
          Type: Api
          Properties:
            Path: /orders/{order_id}
            Method: delete
    Metadata:
      SamResourceId: DeleteOrderFunction
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://coforge-bucket-nd-065/a3f46d2f913672bc6f6e620cd9729de0
      Handler: com.amazonaws.handler.CreateOrderHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: OrdersTable
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: post
    Metadata:
      SamResourceId: CreateOrderFunction
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: orders_table
      AttributeDefinitions:
      - AttributeName: orderId
        AttributeType: S
      KeySchema:
      - AttributeName: orderId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: OrdersTable
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  GetOrderFunction:
    Description: GetOrder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetOrderFunction
      - Arn
  GetOrdersFunction:
    Description: GetOrders Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetOrdersFunction
      - Arn
  UpdateOrderFunction:
    Description: UpdateOrder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UpdateOrderFunction
      - Arn
  DeleteOrderFunction:
    Description: DeleteOrder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DeleteOrderFunction
      - Arn
  CreateOrderFunction:
    Description: CreateOrder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateOrderFunction
      - Arn
